Blizzard/MVC/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using Blizzard.Models;
using System.Web.Security;
using System.Web.Hosting;
using System.Text;
using Newtonsoft.Json;
using Services;
using System.Configuration;
using Core;

namespace Blizzard.Controllers
{
    [Authorize]
    public class CharacterController : Controller
    {
        private string FILENAME = HostingEnvironment.MapPath(ConfigurationManager.AppSettings["LoginFileName"]);
        
        public ActionResult Create()
        {
            PlayerService ps = new PlayerService(FILENAME);
            var p = ps.GetPlayer(User.Identity.Name);

            if (p.Characters.Exists(x => x.Faction == CharacterFaction.Horde && x.Active == true))
            {
                ViewBag.PlayerFaction = "Horde";
            }
            else if (p.Characters.Exists(x => x.Faction == CharacterFaction.Alliance && x.Active == true))
            {
                ViewBag.PlayerFaction = "Alliance";
            }

            CharacterAddModel cm = new CharacterAddModel();
            return View(cm);
        }

        [HttpPost]
        public ActionResult Create(CharacterAddModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CharacterService cs = new CharacterService(FILENAME, User.Identity.Name);
                    cs.AddCharacter(model.Name, model.Faction, model.Race, model.Class);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            return View(model);
        }

        public ActionResult View(Guid Id)
        {
            CharacterService cs = new CharacterService(FILENAME, User.Identity.Name);
            CharacterModel cm = new CharacterModel();
            Character c = cs.GetCharacter(Id);
            cm.Name = c.Name;
            cm.Faction = c.Faction.ToString();
            cm.Race = c.Race.ToString();
            cm.Class = c.Class.ToString();
            cm.Level = c.Level;
            cm.Active = c.Active;

            PlayerService ps = new PlayerService(FILENAME);
            var p = ps.GetPlayer(User.Identity.Name);

            if (p.Characters.Exists(x => x.Faction == CharacterFaction.Horde && x.Active == true))
            {
                ViewBag.PlayerFaction = "Horde";
            }
            else if (p.Characters.Exists(x => x.Faction == CharacterFaction.Alliance && x.Active == true))
            {
                ViewBag.PlayerFaction = "Alliance";
            }

            if(p.Characters.Exists(x => x.Active && x.Level >= 55))
            {
                ViewBag.DeathKnightAvailable = true;
            }
            else
            {
                ViewBag.DeathKnightAvailable = false;
            }

            return View(cm);
        }

        public ActionResult ActiveToggle(Guid Id)
        {
            CharacterService cs = new CharacterService(FILENAME, User.Identity.Name);
            try
            {
                Character c = cs.GetCharacter(Id);
                cs.EditCharacter(c.Id, c.Name, c.Faction.ToString(), c.Race.ToString(), c.Class.ToString(), c.Level, !c.Active);
            }
            catch(Exception e)
            {
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Blizzard/MVC/Views/Character/Create.cshtml
@model Blizzard.Models.CharacterAddModel

@{
    ViewBag.Title = "Create a new Character";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Create", "Character", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Faction, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.Faction, Model.FactionItems, new { id = "FactionDDL", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Faction)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Race, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.Race, Model.RaceItems, new { id = "RaceDDL", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Race)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Class, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.Class, Model.ClassItems, new { id = "ClassDDL", @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Class)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
    <div class="col-md-4">
        <img id="RaceImage" width="300px" height="500px" />
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    var playerFaction = '@ViewBag.PlayerFaction';
    var factionDrop = $('#FactionDDL');
    var raceDrop = $('#RaceDDL');
    var classDrop = $('#ClassDDL');

    $().ready(function () {
        if (playerFaction == "Horde") {
            $('#FactionDDL option:contains(Alliance)').hide();
            $('#FactionDDL option:contains(Horde)').show();

            factionDrop.val("Horde");
        } else if(playerFaction == "Alliance") {
            $('#FactionDDL option:contains(Alliance)').show();
            $('#FactionDDL option:contains(Horde)').hide();

            factionDrop.val("Alliance");
        }

        selectRace(factionDrop.val());

        selectClass(raceDrop.val());

        $('#RaceImage').attr('src', GetRaceImage(raceDrop.val()))

        factionDrop.change(function () {
            selectRace(factionDrop.val());
            selectClass(raceDrop.val());
        });

        raceDrop.change(function () {
            $('#RaceImage').attr('src', GetRaceImage(raceDrop.val()));

            selectClass(raceDrop.val());
        });
    });

    function selectRace(faction) {
        if (faction == "Horde") {
            $('#RaceDDL option:contains(Orc)').show();
            $('#RaceDDL option:contains(Tauren)').show();
            $('#RaceDDL option:contains(BloodElf)').show();
            $('#RaceDDL option:contains(Human)').hide();
            $('#RaceDDL option:contains(Gnome)').hide();
            $('#RaceDDL option:contains(Worgen)').hide();

            $("#RaceDDL").val("Orc");
        }
        else {
            $('#RaceDDL option:contains(Orc)').hide();
            $('#RaceDDL option:contains(Tauren)').hide();
            $('#RaceDDL option:contains(BloodElf)').hide();
            $('#RaceDDL option:contains(Human)').show();
            $('#RaceDDL option:contains(Gnome)').show();
            $('#RaceDDL option:contains(Worgen)').show();

            $("#RaceDDL").val("Human");
        }

        $('#RaceImage').attr('src', GetRaceImage(raceDrop.val()))
    }

    function selectClass(race) {
        if (race == "Orc") {
            $('#ClassDDL option:contains(Warrior)').show();
            $('#ClassDDL option:contains(Druid)').hide();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Warrior");
        }
        else if (race == "Tauren") {
            $('#ClassDDL option:contains(Warrior)').show();
            $('#ClassDDL option:contains(Druid)').show();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Warrior");
        }
        else if (race == "BloodElf") {
            $('#ClassDDL option:contains(Warrior)').hide();
            $('#ClassDDL option:contains(Druid)').hide();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Mage");
        }
        else if (race == "Human") {
            $('#ClassDDL option:contains(Warrior)').show();
            $('#ClassDDL option:contains(Druid)').hide();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Warrior");
        }
        else if (race == "Gnome") {
            $('#ClassDDL option:contains(Warrior)').show();
            $('#ClassDDL option:contains(Druid)').hide();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Warrior");
        }
        else if (race == "Worgen") {
            $('#ClassDDL option:contains(Warrior)').show();
            $('#ClassDDL option:contains(Druid)').show();
            $('#ClassDDL option:contains(DeathKnight)').show();
            $('#ClassDDL option:contains(Mage)').show();

            $("#ClassDDL").val("Warrior");
        }
    }
</script>

}

Blizzard/MVC/Views/Character/View.cshtml
@model Blizzard.Models.CharacterModel

@{
    ViewBag.Title = "View Character";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <hr />
        <div class="form-group">
            <label class="col-md-2 control-label">Name</label>
            <div class="col-md-10">
                <label class="form-control">@Model.Name</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Faction</label>
            <div class="col-md-10">
                <label class="form-control">@Model.Faction</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Race</label>
            <div class="col-md-10">
                <label id="RaceLBL" class="form-control">@Model.Race</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Class</label>
            <div class="col-md-10">
                <label class="form-control">@Model.Class</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Level</label>
            <div class="col-md-10">
                <label class="form-control">@Model.Level</label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Active</label>
            <div class="col-md-10">
                <label class="form-control">@Model.Active</label>
            </div>
        </div>
        <div class="form-group">
            @if(Model.Active)
            {
                <span>@Html.ActionLink("Deactivate Character", "ActiveToggle", "Character", new { Id = Url.RequestContext.RouteData.Values["Id"] }, new { @class = "col-md-12" })</span>
            }
            else
            {
                if(ViewBag.PlayerFaction != null && ViewBag.PlayerFaction != Model.Faction.ToString())
                {
                    <span>Activate Character (Cannot activate this character because he's part of the @Model.Faction)</span>
                }
                @*else if (@Model.Class == Core.CharacterClass.DeathKnight.ToString() && !ViewBag.DeathKnightAvailable)
                {
                    <span>Activate Character (Cannot activate this character because there are no active level 55 characters)</span>
                }*@
                else
                {
                    <span>@Html.ActionLink("Activate Character", "ActiveToggle", "Character", new { Id = Url.RequestContext.RouteData.Values["Id"] }, new { @class = "col-md-12" })</span>
                }
            }
        </div>
    </div>
    <div class="col-md-4">
        <img id="RaceImage" width="100%" />
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $().ready(function () {
        var race = $('#RaceLBL');
        $('#RaceImage').attr('src', GetRaceImage(race.text()))
    });
</script>

}